spring.application.name=url-shortener

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=Rohk_1265

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver
